### ISSUE TITLE
Traceback crash upon launch report

### ISSUE THREAD

**Issue by bramnet** [ramzialhaddadtm/Google-AutoRapper#1]
Happens when I try to launch the exe from command prompt:

`Traceback (most recent call last):
  File "Google_AutoRapper.py", line 2, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\gtts\__init__.py", line 2, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\gtts\tts.py", line 2, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\requests\__init__.py", line 43, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\urllib3\__init__.py", line 8, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "site-packages\urllib3\connectionpool.py", line 7, in <module>
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "socket.py", line 49, in <module>
ModuleNotFoundError: No module named '_socket'`

**Comment by ramzialhaddad** [comment]
Oh this might be a compilation issue. Let me dig into it. Thanks for bringing it up!

**Comment by ramzialhaddad** [comment]
Try to download the new release and try.
https://github.com/ramzialhaddadtm/Google-AutoRapper/releases/tag/v1.1

**Comment by bramnet** [comment]
Log of last run:
`E:\Google.AutoRapper.Build.Fix>"Google AutoRapper.exe"
What do you want your starting words to be? ding
['dingo', 'dingleberry', 'dingy', 'dingus', 'ding dong', 'dinglehopper', 'dinghy', 'dingle ireland', 'dingo dog', 'ding']
6
 dinghy
Do you want to continue or change the magic word? 0 for no, 1 yes, 2 for change? 0
Traceback (most recent call last):
  File "Google AutoRapper.py", line 43, in <module>
  File "site-packages\gtts\tts.py", line 111, in save
  File "site-packages\gtts\tts.py", line 124, in write_to_fp
  File "site-packages\gtts_token\gtts_token.py", line 28, in calculate_token
  File "site-packages\gtts_token\gtts_token.py", line 62, in _get_token_key
AttributeError: 'NoneType' object has no attribute 'group'
[27016] Failed to execute script Google AutoRapper

E:\Google.AutoRapper.Build.Fix>`

It left behind "Google Rap.mp3", but it contains literally nothing (checked with notepad)

**Comment by ramzialhaddad** [comment]
Ah, ok well it seems that Google's Text To Speech (gtts) has updated a full version 2.0.1, and I am using 1.2.2. Hahaha, just need to update and rebuild 1 sec.

**Comment by ramzialhaddad** [comment]
OK try this now, hopefully it will work!
https://github.com/ramzialhaddadtm/Google-AutoRapper/releases/tag/v1.2

**Comment by bramnet** [comment]
Yes, that fixed it. Thanks

**Comment by ramzialhaddad** [comment]
Ayy you're welcome
